name: Brusheros
version: '${version}'
main: pl.joagger.brusheros.BrushPlugin
commands:
  givebrush:
    permission: brusheros.givebrush
    description: Nadaje brusha
    usage: /givebrush (nazwa)
  clear:
    aliases: [ci,clean,clearinvent,clearinventory]
  brushreload:
    permission: brush.reload